FROM python:3.11-slim

WORKDIR /app

# install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY . .

# run Streamlit
CMD ["streamlit", "run", "api/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]